// Generated by tools/build-plates.mjs — do not edit by hand.
// Run `npm run plates` after changing anything in assets-src/projects.

export const plateCounts: Record<string, number> = {
  'booking-app': 4,
  'brb': 1,
  'elevator-2d': 2,
  'elevator-3d': 2,
  'event-day': 2,
  'jutjubic': 4,
  'shelvio': 4,
  'teodity-market': 4,
  'tourflo': 5,
  'travel-vista': 4,
  'unity-2d': 3,
  'unity-3d': 3,
};
