/**
 * Downloads the two typefaces the design calls for and writes local @font-face rules, so
 * the deployed page has no runtime dependency on fonts.googleapis.com.
 *
 * Only the latin and latin-ext subsets are kept — latin-ext is not optional here, it is
 * what carries the ć in Velimirović.
 *
 * Both families are variable fonts, so Google returns the same file for every requested
 * weight. Identical files are stored once and declared with a weight range instead, which
 * is a third of the bytes.
 *
 * Run with `npm run fonts`. Output: public/fonts/*.woff2 and src/styles/_fonts.scss.
 */
import { writeFile, mkdir, readdir, unlink } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const fontsDir = join(root, 'public', 'fonts');

const CSS_URL =
  'https://fonts.googleapis.com/css2?family=Martian+Mono:wght@400;700;800&family=IBM+Plex+Sans:wght@400;500&display=swap';

// Google serves woff2 only to browsers that advertise support for it.
const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';

const KEEP_SUBSETS = new Set(['latin', 'latin-ext']);

const css = await fetch(CSS_URL, { headers: { 'User-Agent': UA } }).then((r) => {
  if (!r.ok) throw new Error(`Google Fonts responded ${r.status}`);
  return r.text();
});

// The CSS is a flat list of @font-face blocks, each preceded by a /* subset */ comment.
const blocks = [...css.matchAll(/\/\*\s*([a-z-]+)\s*\*\/\s*(@font-face\s*\{[^}]*\})/g)].map(
  ([, subset, block]) => ({ subset, block }),
);

if (!blocks.length) throw new Error('Could not parse any @font-face blocks');

// Clear stale files without removing the directory itself — on Windows a shell sitting in
// it, or an editor watching it, makes the rmdir fail.
await mkdir(fontsDir, { recursive: true });
for (const file of await readdir(fontsDir)) {
  if (file.endsWith('.woff2')) await unlink(join(fontsDir, file));
}

/** key: `${family}|${subset}|${hash}` -> face definition */
const faces = new Map();

for (const { subset, block } of blocks) {
  if (!KEEP_SUBSETS.has(subset)) continue;

  const family = /font-family:\s*'([^']+)'/.exec(block)?.[1];
  const weight = /font-weight:\s*([\d ]+)/.exec(block)?.[1].trim();
  const url = /url\((https:[^)]+\.woff2)\)/.exec(block)?.[1];
  if (!family || !url || !weight) continue;

  const buffer = Buffer.from(await fetch(url).then((r) => r.arrayBuffer()));
  const hash = createHash('sha1').update(buffer).digest('hex').slice(0, 8);
  const key = `${family}|${subset}|${hash}`;

  const existing = faces.get(key);
  if (existing) {
    // Same bytes serving another weight — widen the declared range instead of re-saving.
    existing.weights.push(Number(weight));
    continue;
  }

  const slug = family.toLowerCase().replace(/\s+/g, '-');
  const file = `${slug}-${subset}.woff2`;
  await writeFile(join(fontsDir, file), buffer);

  faces.set(key, {
    family,
    file,
    weights: [Number(weight)],
    style: /font-style:\s*(\w+)/.exec(block)?.[1] ?? 'normal',
    unicodeRange: /unicode-range:\s*([^;]+);/.exec(block)?.[1],
  });
}

// The url is root-absolute because these files are served from public/ untouched; a
// relative url would make the Angular stylesheet bundler try to resolve it at build time.
const out = [
  '// Generated by tools/fetch-fonts.mjs — do not edit by hand.',
  '// Run `npm run fonts` to refresh.',
  '',
];

for (const face of faces.values()) {
  const min = Math.min(...face.weights);
  const max = Math.max(...face.weights);
  out.push(
    '@font-face {',
    `  font-family: '${face.family}';`,
    `  font-style: ${face.style};`,
    `  font-weight: ${min === max ? min : `${min} ${max}`};`,
    '  font-display: swap;',
    `  src: url('/fonts/${face.file}') format('woff2');`,
    ...(face.unicodeRange ? [`  unicode-range: ${face.unicodeRange};`] : []),
    '}',
    '',
  );
}

await mkdir(join(root, 'src', 'styles'), { recursive: true });
await writeFile(join(root, 'src', 'styles', '_fonts.scss'), out.join('\n'), 'utf8');

console.log(`Saved ${faces.size} woff2 files into public/fonts.`);
